### ISSUE TITLE
Mote-Utility.lua:14 Attempt to Call global 'error' (a nil value)

### ISSUE THREAD

**Issue by kbeezie** [Kinematics/GearSwap-Jobs#1]
I got the following error
Mote-Utility.lua:14: attempt to call global 'error' (a nil value)

I also updated that file to the one that was updated 5 minutes ago in attempt to fix it, shows same problem on reload.

**Comment by kbeezie** [comment]
As an update, I was using set_macro_page(20,1), because the older windower command had the book first, then page. The config works if I swap that to 1,20, but the error handling still seems to fail.

**Comment by Kinematics** [comment]
Fixed the error issue with 9d21107a04326391caa974757575bb17efe4ac18.

I'll consider changing the syntax to (book,set), but I wanted it so that you could just use (set) without specifying the book in order to change between sets within a single book, which is why set is first.
