### ISSUE TITLE
BLM.lua custom spell map commit broke midcast for nukes

### ISSUE THREAD

**Issue by AlanWarren** [Kinematics/GearSwap-Jobs#14]
job_midcast is ignoring the new spellMap functionality you built in.
 i.e. sets.midcast.FastRecast is being used unconditionally. 

Thanks!

**Comment by Kinematics** [comment]
Can you elaborate?  sets.midcast.FastRecast should be the base layer for equipment selection, and anything else gets added on top of it (replacing whatever FastRecast had, if applicable).

If you're not seeing more specific replacement gear, for which spells is that occurring, and what various modes (if not defaults)?

Also, are you getting the info on what gear is being equipped from showswaps?

**Comment by AlanWarren** [comment]
My apologies for being vague. I'm actually trying to help a friend out, so it's a little awkward to test. He said no matter what elemental magic he cast, it was sticking him in sets.midcast.FastRecast. He was testing with both high tier and low teir spells. 

I added the get_nuke_class() function back, along with the following, in job_midcast, and it fixed it for him. 

if spell.skill == 'Elemental Magic' then
    if state.CastingMode == 'Proc' then
        add_to_chat(15,'Proc mode, no damage gear for midcast.')
        eventArgs.handled = true
    else
        classes.CustomClass = get_nuke_class(spell, action, spellMap)
    end
end

I just assumed equipping sets.midcast.FastRecast wasn't allowing the custom class to be considered. 

If this is working for you, I'll have him download everything again and try again. 

Thanks

**Comment by AlanWarren** [comment]
You can close this. Somhow he was missing the job_get_spell_map function. Sorry to bother.

**Comment by Kinematics** [comment]
Closing, per solved.
