### ISSUE TITLE
cancel spells

### ISSUE THREAD

**Issue by sebyg666** [Kinematics/GearSwap-Jobs#4]
couldnt speak to you on irc so i thaught id raise an issue here so you would be able to find it.
## in mote-utility.lua you have:

function cancel_conflicting_buffs(spell, action, spellMap, eventArgs)
    if cancel_spells_to_check:contains(spell.english) or cancel_types_to_check:contains(spell.type) then
        if spell.action_type == 'Ability' then
            local abil_recasts = windower.ffxi.get_ability_recasts()
            if abil_recasts[spell.index] > 0 then
                add_to_chat(123,'Cancel abort: Ability waiting on recast.')
                eventArgs.cancel = true
                return
            end
        elseif spell.action_type == 'Magic' then
            local spell_recasts = windower.ffxi.get_spell_recasts()
            if spell_recasts[spell.index] > 0 then
                add_to_chat(123,'Cancel abort: Spell waiting on recast.')
                eventArgs.cancel = true
                return
            end
##         end

and it just wasnt working propally for me. the add_to_chat wasnt fireing ect.
Anyway through alot of testing ect, i found that spell.index is off by 1.
If you use ""if spell_recasts[spell.index + 1] > 0 then"" it works flawlessly.
noticed you dont have the function utilised in your gearswap job files and figured  it may be cos it doesnt work, anyway this fixes it for me. hope this helps.

**Comment by Kinematics** [comment]
Fixed with commit f8ef0d01c1bce5528ba008b06177fc8fa7972dfc

Only valid on dev at the moment, since the spell table structure was revised to include recast_id instead of index.
