### ISSUE TITLE
SMN.lua

### ISSUE THREAD

**Issue by Crevox** [Kinematics/GearSwap-Jobs#49]
1) Line 58: Ramuh's Astral Flow is spelled "Judgement Bolt" which is incorrect, causing no gearswap to occur. The proper spelling is "Judgment Bolt."

2) Mana Cede and Elemental Siphon sets do not function. They must be added as midcasts. This is one example of how it's done to better understand this (added in job_midcast, preferably moved over to proper midcast system):

```
if (spell.english=='Mana Cede') then
        equip(sets.precast.JA['Mana Cede'])
    elseif (spell.english=='Elemental Siphon')  then
        equip(sets.precast.JA['Elemental Siphon'])
end
```

3) The "siphon system" is not working properly. As an example of a bad scenario, In the event of 2 dark weathers on a lightsday, a light spirit is used, which offers greatly reduced MP compared to a dark spirit.

**Comment by Crevox** [comment]
Updated with another issue.

**Comment by Kinematics** [comment]
First, sorry for not noticing this issue.  No one's used my issue tracker in so long, forgot it existed.

1) Fixed.
2) Rename the sets as sets.midcast['Mana Cede'] and sets.midcast['Elemental Siphon'] to force those sets to be used during midcast.  You shouldn't have to modify the rules.  I'll need to do testing on my own for how they work.
3) Fixed.

**Comment by Kinematics** [comment]
Closing this since the bugs were fixed.  The potential remaining issue is a logic one, not a code one.
