### ISSUE TITLE
Scholar Desert boots

### ISSUE THREAD

**Issue by yanosuke** [Kinematics/GearSwap-Jobs#54]
I've tried numerous things, but I'm just unable to have my Desert boots equipped when sandstorm buff is on my scholar. I'm not sure why it's not working.

**Comment by Kinematics** [comment]
Have use modified your idle set in customize_idle_set(), when world.weather_element == 'Earth'?

**Comment by yanosuke** [comment]
I will try this and see if it works. Still not sure why buffactive['Sandstorm'] doesn't work though.

**Comment by Kinematics** [comment]
Closing, since no feedback from the original poster on the solution provided.  Assuming it worked.
