### ISSUE TITLE
Sneak spell not replacing sneak buff

### ISSUE THREAD

**Issue by geekgirl101** [Kinematics/GearSwap-Jobs#60]
When casting Sneak or Spectral Jig it does not replace the sneak buff if it's already active.  I've added these lines in to remove the sneak buff before casting just before the End at the first If/End in the job_midcast function:

Jobs using WHM/SCH/RDM:

```
elseif spell.english == 'Sneak' and buffactive.sneak and spell.target.type == 'SELF' then
    send_command('cancel 71')
    cast_delay(0.3)
```

Jobs using DNC:

```
elseif spell.english == 'Spectral Jig' and buffactive.Sneak then
    send_command('cancel 71')
```

**Comment by Kinematics** [comment]
That should already be handled globally in Mote-Globals, where the `user_precast` function calls the utility function `cancel_conflicting_buffs`.  Do you have the cancel addon loaded?  I also see that you're using numbers for the buff, so are perhaps using the plugin version; try using the addon version if so.

**Comment by Kinematics** [comment]
Ah, I thought I'd answered this just a bit ago.  You also wrote the comment on the code checkin.

In any case, remove the code from the job files that you added, and if the cancel addon is properly loaded, add an add_to_chat line in the Mote-Globals function to make sure it's being called.

**Comment by geekgirl101** [comment]
Yeah I was just using the plugin, I've tried the addon and it's now working.  Thank you.
