### ISSUE TITLE
sets.self_healing Problem.

### ISSUE THREAD

**Issue by Selindrile** [Kinematics/GearSwap-Jobs#62]
(Using Live, not dev Luas)

Not sure why but sets.self_healing only seems to work properly for Blu,combining with sets.midcast['Blue Magic'].Healing when targetting myself.

On Pld or Rdm though it does not properly combine when I cure myself, it simply uses sets.midcast.Cure regardless of target.

Perhaps I have to use a different set for combining with non-Blu cures? Or perhaps it's not implemented yet for healing magic?

**Comment by Kinematics** [comment]
Answered in game.

Implement with a check in job_post_midcast.  Pld and Rdm do not have this implemented in the default files.

**Comment by Selindrile** [comment]
Tried adding

function user_post_midcast(spell, action, spellMap, eventArgs)
        if spellMap == 'Cure' and spell.target.type == 'SELF' and sets.self_healing then
            equip(sets.self_healing)
        end
end

to my Selindrile-Globals.lua and no joy, hoping someone might correct my mistake.

**Comment by Kinematics** [comment]
Aha... Ok, this is similar to an issue that someone else had.  Finally figured it out.  user_post_\* functions aren't actually implemented.  I need to fix that.

Ok, is fixed on dev, now.  Next merge to live should be soon.

**Comment by Selindrile** [comment]
Ahhh, makes sense, I'll wait for the merge and that update rather than adding code to each sidecar, many thanks.

**Comment by Selindrile** [comment]
Changed, seems to be mostly working fine, however does not work with with Afflatus Solace up.

**Comment by Kinematics** [comment]
Open another issue for whatever the other problem is.
