### ISSUE TITLE
A few more spell.skill instances using CamelCase

### ISSUE THREAD

**Issue by AlanWarren** [Kinematics/GearSwap-Jobs#7]
SCH.lua, on lines 448, 454
BLM.lua, on lines 272, 284
WHM.lua on line 262
RDM.lua on lines 230, 232

After merging in your latest commit fixing spell.skill, I noticed high tier nukes weren't switching sets in BLM.lua.  Changing the above lines resolved the issue. (also noted other files with similar issue) 

Thanks

**Comment by Kinematics** [comment]
Thanks.  Fixed those, as well as some other instances that I'd missed before.
Fixed with commit 114375d55a4d622b18ddecad4a1ad7a3afae98b5.
