### ISSUE TITLE
Blue Mage, Not sure why a castingmode isn't working.

### ISSUE THREAD

**Issue by Selindrile** [Kinematics/GearSwap-Jobs#72]
My Bluemage Sidecar: http://pastebin.com/7BCfem7X

Not quite sure why:

sets.midcast['Blue Magic'].Physical.Resistant
sets.midcast['Blue Magic'].Magical.Resistant

And sets like

sets.midcast['Blue Magic'].PhysicalStr.Resistant

Aren't working, I've tried looking at Blm.Lua and the Mode-Includes, but not sure why these won't work but sets like this do: 

sets.midcast['Elemental Magic'].Resistant

**Comment by yanosuke** [comment]
This gave me an incredible headache trying to figure out why I could not make this work on my custom scholar lua. It basically comes down to this, mote's lua's only handle 1 return value. The Lua language can handle multiple values, but the way Mote has them setup it will only interpret 1 return.

In your example, when blue magic is cast, the script will determine if the spell is physical or magical and it will return it's findings as "Physical" or "Magical". It will then search your sidecar for your sets.midcast['Blue Magic'].Physical or sets.midcast['Blue Magic'].Magical depending on the spell type.

It's the fact the script has already returned a value of "Physical" or "Magical" that it will not interpret any other values. You might be able to edit the midcast function in a way where your script will do the interpreting. Then you can let it return 4 different values such as "Physical", "Magical", PhysicalResistant","MagicalResistant" depending on your option values. Not sure if it would work though.

**Comment by Selindrile** [comment]
Hrm, seems odd that it would be set up to recognize things like engaged.PDT.Acc.Dagger and even sets.midcast['Elemental Magic'].HighTierNuke.Resistant etc etc, and not be able to do the same for blue magic.

**Comment by Kinematics** [comment]
'Resistant' is a value for casting mode. 'Physical' is a spell mapping.  The above set names 'should' be valid.
`sets.midcast['Blue Magic']` is selected for spell.skill.  `Physical` is appended for spell map.  `Reisistant` is appended for casting mode.

I'd ask if you're checking that the spell you're testing is in fact in that specific spell map list.  For example, the only spell under `Physical` is Bilgestorm.  All the others are Physical + some stat.

Also, turn on debugmode and look at the gear sets it's trying to use by default.  That can provide a better clue as to what's not working.

**Comment by Selindrile** [comment]
Thank you for your input, the sets were indeed valid, the testing was what was flawed, I mistakenly thought a few other spells used the generic "physical"  set, I should have checked the spellmap.
