### ISSUE TITLE
File too large for GS?

### ISSUE THREAD

**Issue by yanosuke** [Kinematics/GearSwap-Jobs#75]
I'm having a little issue and I was wondering if it's possible because of file size. Is there a limit in size that GS can handle without hickups? Sometimes after a WS, my gear won't swap back to engaged gear, and other times it will. Likewise, I created a regen counter for my SCH that is accurate. Most of the time it will work perfectly, but sometimes it will be inaccurate. Meaning it was not able to identify a piece of equipment at the time of timer creation.

The way I've done all my alterations is to put all of them in pretty much 1 file. My own include. It will have all the functions of all my jobs and characters that are different from mote's job lua file. It's always worked fine, but now it's having these issues. This file is now 651 lines long. Is this simply too long? If it is, I can split up the codes by character, which isn't an issue, but would like to keep it like this if possible.

**Comment by z16** [comment]
This is nowhere near too large, there is no file size limit I'm aware of, but Windower uses Lua files that have almost 20k lines and 5MB in file size, so that is most definitely not an issue. There have been some recent GS changes that may have screwed something up, you should probably post your user files somewhere we can see so it's easier to debug. Also, if you find a reliable way to debug it, you'd help a lot with the process.

**Comment by yanosuke** [comment]
Yeah, that's what I thought as well. There should be no issue. normally though if there's a typo somewhere or something is placed incorrectly, it will simply not work or it will work in an unintended way. It's just weird that sometimes it works and sometimes it doesn't. I will try and debug it and see what is causing the issue, but I wouldn't mind a second set of eyes. Let me see if I can upload my lua somewhere

EDIT: Well, for some reason it is equipping the proper gear after WS now at all times. I also discovered how the regen counter issue occurs, just not sure why. If I use Perpetuance and very quickly use Regen right after, it will equip my aftercast gear during midcast, so the full duration bonus isn't applied. If I use Perpetuance a second or so before using regen, it will properly equip aftercast gear after the spell is cast, thus benefiting from all the bonuses. Gotta figure out what's causing it to equip aftercast during midcast in that situation,

**Comment by yanosuke** [comment]
Here's my include:
https://www.dropbox.com/s/7iahrr1mvppz9sy/Yano-Include.lua?dl=0

The files the include calls for just contain a bunch of variables, so no actual code.
I think the cancel addon has something to do with it. Maybe GS tries to cancel a buff, processes it, and then equips the idle set. Even before casting is complete and even though there are no buffs present to be canceled. Only buffs are light arts and perpetuance.

EDIT: Seems to have nothing to do with any buff being canceled. And Regen seems to get its bonuses ok as long as I don't cast regen right after using perpetuance.

EDIT2: I've adjusted my very situational auto-perpetuance for regen function. Raised the delay from 1.1 to 1.3, it it now equips midcast properly. Switches from precast to aftertcast to midcast, but works good enough as a work around for this very situational funtion.
WSing works perfectly without flaws. I don't think it has anything to do at all with GS or the codes that I'm using, but rather an external source that might be causing some sort of interference at certain times.

EDIT3: There still is an issue with Regen gear sometimes not being equipped properly. If it persists and I can't find out a fix, I'll turn it into it's own issue.
